go

diff --git a/gazes-download b/gazes-download
--- a/gazes-download
+++ b/gazes-download
@@ -1,101 +1,53 @@
+
 #!/bin/bash
 
 prog_name=$(basename "$0")
 
-sub_help(){
-    echo "Usage: $prog_name <subcommand> [options]"
-    echo "Subcommands:"
-    echo "  install <id> <episode>"
-    echo ""
-}
+watch() {
 
-fetch_anime_info() {
-    local id="$1"
-    curl -s "https://api.gazes.fr/anime/animes/$id"
-}
-
-get_title() {
-    local anime="$1"
-    echo "$anime" | jq -r '.data.title | ascii_downcase | gsub(" ";"-")'
-}
-
-get_episode_count() {
-    local anime="$1"
-    echo "$anime" | jq -r '.data.episodes | length'
-}
-
-download_episode() {
-    local id="$1"
-    local episode="${2:-1}"
-
-    local anime
-    anime=$(fetch_anime_info "$id")
-    local title
-    title=$(get_title "$anime")
-    local episodes
-    episodes=$(get_episode_count "$anime")
-
-    if [[ "$title" == "null" ]]; then
-        echo "This anime does not exist."
-        exit 1
-    fi
-
-    if [[ "$episode" == *".."* ]]; then
-        local from=$(echo "$episode" | awk -F' +|[.][.]' '/^[^#]/{print $1}')
-        local to=$(echo "$episode" | awk -F' +|[.][.]' '/^[^#]/{print $2}')
-        
-        echo "Downloading episodes $from to $to"
-        
-        for ((i = from; i <= to; i++)); do
-            download_episode "$id" "$i"
-            sleep 1
-        done
-
-        return
-    fi
-
-    local video_url
-    video_url=$(curl -s "https://api.gazes.fr/anime/animes/$id/$episode" | jq -r '.data.vostfr.videoUri')
-
-    local episode_file="$title/episode-$episode.mkv"
-
-    [ -f "$episode_file" ] && rm "$episode_file"
-
-    mkdir -p "$title"
-
-    start=$(date +%s)
-    
-    ffmpeg -loglevel quiet -i "$video_url" -c copy -bsf:a aac_adtstoasc "$episode_file" &
-    ffmpeg_pid=$!
-
-    echo ""
-    echo "Downloading $title episode $episode"
-
-    spinner="/-\\|"
-    while kill -0 $ffmpeg_pid 2>/dev/null; do
-        for i in $(seq 0 3); do
-            echo -ne "\r${spinner:$i:1} "
-            sleep 0.1
-        done
+    while getopts "e:l:" opt; do
+        case ${opt} in
+            e )
+                episode=$OPTARG
+                ;;
+            l )
+                lang=$OPTARG
+                ;;
+            \? )
+                echo "Invalid option: -$OPTARG" 1>&2
+                exit 1
+                ;;
+            : )
+                echo "Invalid option: -$OPTARG requires an argument" 1>&2
+                exit 1
+                ;;
+        esac
     done
+    shift $((OPTIND -1))
 
-    end=$(date +%s)
-    echo -e "\rDownloaded $(du -h "$episode_file" | cut -f1) in $(expr $end - $start) seconds.\n"
+    title=$(printf %s "$1" | jq -sRr @uri)
+    episode=${episode:-1}
+    lang=${lang:-vostfr}
+
+    anime_info=$(curl -s "https://api.gazes.fr/anime/animes?title=$title")
+    anime_id=$(echo "$anime_info" | jq .data[0].id)
+    real_title=$(echo "$anime_info" | jq -r .data[0].title | tr ' ' '-')
+    anime=$(curl -s "https://api.gazes.fr/anime/animes/$anime_id/$episode")
+    anime_video=$(echo "$anime" | jq -r ".data.$lang.videoUri")
+
+    if [[ "$anime_video" = "null" ]]; then
+        anime_video=$(echo "$anime" | jq -r ".data.vostfr.videoUri")
+        echo "$anime_video"
+    fi
+
+    temp_file="/tmp/${real_title}_${episode}_$(cat /dev/urandom | tr -cd 'a-f0-9' | head -c 32).m3u8"
+    curl -s -o "$temp_file" "$anime_video"
+    sed -i 's/{PROXY_URL}/https:\/\/proxy.ketsuna.com/g' "$temp_file"
+
+    vlc "$temp_file" > /dev/null
 }
 
-subcommand=$1
-case $subcommand in
-    "" | "-h" | "--help")
-        sub_help
-        ;;
-    *)
-        shift
-        download_episode "$subcommand" "$@"
-        if [ $? = 127 ]; then
-            echo "Error: '$subcommand' is not a known subcommand." >&2
-            echo "       Run '$prog_name --help' for a list of known subcommands." >&2
-            exit 1
-        fi
-        ;;
-esac
-
+if [[ "$1" = "watch" ]]; then
+    shift
+    watch "$@"
+fi
